In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
from pickle import load
import keras

Using TensorFlow backend.


In [2]:
songs = pd.read_csv("song_list5.csv")

In [3]:
songs.head()

songid       artist                    track  danceability  \
0  5X4Qm0rVLcZeeO4tSDmBg3   Jack Bruce  Running Thro' Our Hands         0.456   
1  1pNpt53PZPet9dvJN3RKGr   Prefuse 73        Parachute Panador         0.535   
2  3oxz2oCzAWdPzA6In2zA5u  Pasion Vega   La Gata Bajo La Lluvia         0.294   
3  05JGVUwt7XJk5FPqH0Wsch   Jonny Lang             Walking Away         0.563   
4  3xdgCFMTn6ut8fZYxfAuR0         Skye         All the Promises         0.358   

   energy  key  loudness  mode  speechiness  acousticness  instrumentalness  \
0   0.255  9.0   -15.805   1.0       0.0480       0.94600          0.170000   
1   0.806  7.0   -10.289   1.0       0.0642       0.00436          0.019100   
2   0.482  5.0    -6.406   1.0       0.0430       0.46300          0.000000   
3   0.631  0.0    -5.144   1.0       0.0324       0.06350          0.000008   
4   0.611  2.0    -9.752   0.0       0.0454       0.51500          0.000468   

   liveness  valence    tempo  duration_ms  time_signature  
0     0.951   0.0532  116.424     253067.0             4.0  
1     0.457   0.3760   90.089      63733.0             4.0  
2     0.335   0.2040  166.693     255280.0             3.0  
3     0.163   0.5400  115.657     254827.0             4.0  
4     0.149   0.1640  171.596     256933.0             4.0

In [4]:
features = songs[[
    "danceability", "energy", "key", "loudness", "mode", "speechiness", 
    "acousticness", "instrumentalness", "liveness", "valence", "tempo", 
    "duration_ms", "time_signature"]].to_numpy()

In [5]:
features[0]

array([ 4.56000e-01,  2.55000e-01,  9.00000e+00, -1.58050e+01,
        1.00000e+00,  4.80000e-02,  9.46000e-01,  1.70000e-01,
        9.51000e-01,  5.32000e-02,  1.16424e+02,  2.53067e+05,
        4.00000e+00])

In [6]:
scaler = load(open('scaler.pkl', 'rb'))

In [7]:
x_train = scaler.transform(features)

In [8]:
x_train[0:5]

array([[-0.47695143, -1.43616823,  1.03467011, -1.32564479,  0.70711739,
        -0.34028656,  1.91669133, -0.14321669,  3.87500921, -1.70714343,
        -0.17066299,  0.03404049,  0.24368604],
       [-0.03739907,  0.69843612,  0.47428756, -0.17173186,  0.70711739,
        -0.1963104 , -0.87635746, -0.58458172,  1.27879637, -0.49117162,
        -1.06220066, -1.51723037,  0.24368604],
       [-1.37831198, -0.55675773, -0.08609498,  0.64056762,  0.70711739,
        -0.38472365,  0.48403919, -0.64044701,  0.6376264 , -1.13908721,
         1.53112958,  0.05217227, -1.94432308],
       [ 0.11839165,  0.02047648, -1.48705135,  0.90457018,  0.70711739,
        -0.47893027, -0.70093914, -0.64042226, -0.26631816,  0.12660836,
        -0.19662879,  0.04846071,  0.24368604],
       [-1.02221893, -0.05700462, -0.9266688 , -0.05939479, -1.41419234,
        -0.36339385,  0.63827917, -0.63907816, -0.33989504, -1.28976525,
         1.69711436,  0.0657158 ,  0.24368604]])

In [9]:
encoder = load_model('encoder.h5')

In [10]:
preds = encoder.predict(x_train)

In [11]:
preds[0:5]

array([[1.1816081, 1.7670339],
       [4.655777 , 3.1689727],
       [2.9014647, 1.7386702],
       [4.1706915, 1.6202143],
       [4.307556 , 7.3538566]], dtype=float32)