In [1]:
# These are all the imports I used in this notebook
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
from pickle import load
import keras

Using TensorFlow backend.


In [2]:
# this is just to test the model by loading in data. the API is where the information will actually come from
songs = pd.read_csv("song_list5.csv")

In [3]:
# These are the features and in this order
# this is the information you will need from the 
features = songs[[
    "danceability", "energy", "key", "loudness", "mode", "speechiness", 
    "acousticness", "instrumentalness", "liveness", "valence", "tempo", 
    "duration_ms", "time_signature"]].to_numpy()

In [4]:
# this is what the data will look like
# notice here that the data has one only one set of brackets around the vector
features[0]

array([ 4.56000e-01,  2.55000e-01,  9.00000e+00, -1.58050e+01,
        1.00000e+00,  4.80000e-02,  9.46000e-01,  1.70000e-01,
        9.51000e-01,  5.32000e-02,  1.16424e+02,  2.53067e+05,
        4.00000e+00])

In [5]:
# The takes the data and turns it into a 2 dimentional numpy array
new_df = np.atleast_2d(features[0])

In [6]:
# It will Look like this
# now there are 2 sets of brackets around the vector
new_df

array([[ 4.56000e-01,  2.55000e-01,  9.00000e+00, -1.58050e+01,
         1.00000e+00,  4.80000e-02,  9.46000e-01,  1.70000e-01,
         9.51000e-01,  5.32000e-02,  1.16424e+02,  2.53067e+05,
         4.00000e+00]])

In [7]:
# The 13 has to be the second number in order to be fed into the model
new_df.shape

(1, 13)

In [8]:
# This is how to load in the scaler
scaler = load(open('scaler.pkl', 'rb'))

In [9]:
# Using the scaler to transform the data
x_train = scaler.transform(new_df)

In [10]:
# after the information is scaled it will look like this rather than the scientific notation
# it will still have 2 sets of brackets around the vector
# its shape will still have 13 as the second number
x_train

array([[-0.47695143, -1.43616823,  1.03467011, -1.32564479,  0.70711739,
        -0.34028656,  1.91669133, -0.14321669,  3.87500921, -1.70714343,
        -0.17066299,  0.03404049,  0.24368604]])

In [11]:
# this is how to load in the model
encoder = load_model('encoder.h5')

In [12]:
# this is how to make the predictions with the model
preds = encoder.predict(x_train)

In [13]:
# the predictions will be a vector containing 2 numbers in it
# these 2 numbers will then be saved into a database along with the track_id
preds

array([[1.181608 , 1.7670343]], dtype=float32)

In [14]:
# from here a K nearest neighbors will be preformed on the data base to find the x number of songs closest to our song in the database.
# x is the number of songs requested by the user and will be given to us by the back end
# if a number isn't given to us by the back end than default the number to 5